name: Merge back in develop

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to merge in develop'
      target_branch:

jobs:
  merge-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git checkout -B ${{ github.event.inputs.target_branch }}; git checkout -B ${{ github.event.inputs.target_branch }} refs/remotes/origin/${{ github.event.inputs.target_branch }}
          git config push.default simple
          git config user.email "tecnologia@passeidireto.com"
          git config user.name "Github Actions"
          git merge remotes/origin/${{ github.event.inputs.branch }} --no-ff --no-commit

          [ -f package.json ] && git reset HEAD package.json || echo "package.json doesn't exist"
          [ -f package.json ] && git checkout -- package.json || echo "package.json doesn't exist"

          echo '#============ Auto merge ===============#'
          git commit -m "Auto-merge" --allow-empty
          git push https://github.com/jhonsouza/rest-api-4.git ${{ github.event.inputs.target_branch }}:${{ github.event.inputs.target_branch }}
          # ssh-agent -k