name: merge back

on: workflow_call

jobs:
  merge-back:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config user.name pd-bot
          git config user.email admin@passeidireto.com
      - name: Merge back
        run: |
          git fetch --unshallow origin develop
          git switch develop
          git merge --no-ff -m 'chore: merge-back' main
          git push