name: Merge back in develop

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch to merge in develop'
      target_branch:

jobs:
  merge-back:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0
      - name: Create PR
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: ${{ github.event.inputs.target_branch }}
          github_token: ${{ secrets.GIT_TOKEN }}
          pr_title: "[AUTOMATED] Auto-merge ${{ github.event.inputs.branch }} into develop"
          pr_body: "Automated Pull Request"
          pr_assignee: $GITHUB_ACTOR
      - name: auto merge
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GIT_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          