name: Tag test


on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to deploy"
        type: boolean
        default: true

jobs:
  create_tag:
    name: create git tag
    uses: ./.github/workflows/generate-tag.yaml
    secrets: inherit

  teste:
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "tag: ${{ github.ref }}"
          read currentTag previousTag <<< "$(git tag --sort=-creatordate | grep v | head -n 2 | tr '\n' ' ')"
          echo "currentTag: $currentTag"
          echo "previousTag: $previousTag"
          if [ git diff $previousTag $currentTag --quiet ]; then
            echo "No changes between $previousTag and $currentTag"
          else
            echo "Changes between $previousTag and $currentTag"
          fi
