name: Create release and deploy to Tst

on:
  push:
    branches:
      - release/*
  workflow_dispatch:
    inputs:
      create_release:
        description: "Create release branch from develop"
        type: boolean
        default: true
      version_type:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs: 
  teste:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.create_release }}
          echo ${{ inputs.version_type }}
      